name: 01 - CI Desarrollo (Build Check)

on:
  push:
    branches: ["develop"]

jobs:
  build-dev:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Valdo-Backend

    steps:
      - name: Checkout del c√≥digo
        uses: actions/checkout@v4

      - name: Configurar el JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          cache-dependency-path: ./Valdo-Backend/pom.xml

      - name: Compilar con Maven
        run: mvn clean compile




